version: '3.8'

services:
  backend:
    build: .
    container_name: aws-3tier-backend
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped

