
# Use an official Nginx image as a base
FROM nginx:alpine

# Copy the built React app's static files into Nginx's default directory
COPY ./build /usr/share/nginx/html

# Copy the Nginx config file into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the host
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
